---
- name: Install NVIDIA Container Tools RPM
  ansible.builtin.dnf:
    name: "nvidia-container-toolkit-{{ nvidia_driver_container_tools_version_release }}"
    state: present

- name: Check if CDI configfile exists
  ansible.builtin.stat:
    path: /etc/cdi/nvidia.yaml
  register: nvidia_driver_cdi_config_file

- name: Configure NVIDIA container runtime
  when:
    - nvidia_driver_generate_cdi_config | bool
    - not nvidia_driver_cdi_config_file.stat.exists
    - not (_nvidia_driver_is_host_mode | bool)

  block:
    - name: Ensure CDI directory exists
      ansible.builtin.file:
        path: /etc/cdi
        state: directory
        mode: "0755"
        owner: root
        group: root

    - name: Configure NVIDIA container runtime
      ansible.builtin.command: nvidia-ctk runtime configure --runtime=containerd
      changed_when: true

    - name: Generate NVIDIA CDI configuration
      ansible.builtin.command: nvidia-ctk cdi generate --output=/etc/cdi/nvidia.yaml
      changed_when: true
